// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lz4CompressEngineRun_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_compress (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inStream_dout,
        inStream_empty_n,
        inStream_read,
        compressdStream_din,
        compressdStream_full_n,
        compressdStream_write,
        compressdStream_num_data_valid,
        compressdStream_fifo_cap,
        arrayidx48_promoted176_reload,
        arrayidx42_3_promoted174_reload,
        arrayidx71_promoted172_reload,
        arrayidx61_promoted170_reload,
        arrayidx54_promoted168_reload,
        sub27,
        dict_3_address0,
        dict_3_ce0,
        dict_3_we0,
        dict_3_d0,
        dict_3_q0,
        dict_2_address0,
        dict_2_ce0,
        dict_2_we0,
        dict_2_d0,
        dict_2_q0,
        dict_1_address0,
        dict_1_ce0,
        dict_1_we0,
        dict_1_d0,
        dict_1_q0,
        dict_address0,
        dict_ce0,
        dict_we0,
        dict_d0,
        dict_q0,
        present_window_15_out,
        present_window_15_out_ap_vld,
        present_window_14_out,
        present_window_14_out_ap_vld,
        present_window_13_out,
        present_window_13_out_ap_vld,
        present_window_12_out,
        present_window_12_out_ap_vld,
        present_window_11_out,
        present_window_11_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] inStream_dout;
input   inStream_empty_n;
output   inStream_read;
output  [31:0] compressdStream_din;
input   compressdStream_full_n;
output   compressdStream_write;
input  [3:0] compressdStream_num_data_valid;
input  [3:0] compressdStream_fifo_cap;
input  [7:0] arrayidx48_promoted176_reload;
input  [7:0] arrayidx42_3_promoted174_reload;
input  [7:0] arrayidx71_promoted172_reload;
input  [7:0] arrayidx61_promoted170_reload;
input  [7:0] arrayidx54_promoted168_reload;
input  [31:0] sub27;
output  [9:0] dict_3_address0;
output   dict_3_ce0;
output   dict_3_we0;
output  [431:0] dict_3_d0;
input  [431:0] dict_3_q0;
output  [9:0] dict_2_address0;
output   dict_2_ce0;
output   dict_2_we0;
output  [431:0] dict_2_d0;
input  [431:0] dict_2_q0;
output  [9:0] dict_1_address0;
output   dict_1_ce0;
output   dict_1_we0;
output  [431:0] dict_1_d0;
input  [431:0] dict_1_q0;
output  [9:0] dict_address0;
output   dict_ce0;
output   dict_we0;
output  [431:0] dict_d0;
input  [431:0] dict_q0;
output  [7:0] present_window_15_out;
output   present_window_15_out_ap_vld;
output  [7:0] present_window_14_out;
output   present_window_14_out_ap_vld;
output  [7:0] present_window_13_out;
output   present_window_13_out_ap_vld;
output  [7:0] present_window_12_out;
output   present_window_12_out_ap_vld;
output  [7:0] present_window_11_out;
output   present_window_11_out_ap_vld;

reg ap_idle;
reg inStream_read;
reg compressdStream_write;
reg present_window_15_out_ap_vld;
reg present_window_14_out_ap_vld;
reg present_window_13_out_ap_vld;
reg present_window_12_out_ap_vld;
reg present_window_11_out_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln93_reg_2712;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    compressdStream_blk_n;
wire    ap_block_pp0_stage2_grp2;
reg    inStream_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] i_1_reg_2651;
reg    ap_block_state5_pp0_stage1_iter1_grp1;
reg    ap_block_pp0_stage1_11001;
reg   [31:0] i_1_reg_2651_pp0_iter1_reg;
reg   [7:0] present_window_11_load_reg_2657;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg    ap_block_pp0_stage1_subdone;
reg   [7:0] present_window_11_load_reg_2657_pp0_iter1_reg;
reg   [7:0] present_window_11_load_reg_2657_pp0_iter2_reg;
reg   [7:0] present_window_11_load_reg_2657_pp0_iter3_reg;
reg   [7:0] present_window_12_load_reg_2671;
reg   [7:0] present_window_12_load_reg_2671_pp0_iter1_reg;
reg   [7:0] present_window_12_load_reg_2671_pp0_iter2_reg;
reg   [7:0] present_window_13_load_reg_2685;
reg   [7:0] present_window_13_load_reg_2685_pp0_iter1_reg;
reg   [7:0] present_window_13_load_reg_2685_pp0_iter2_reg;
reg   [7:0] present_window_14_load_reg_2699;
reg   [7:0] present_window_14_load_reg_2699_pp0_iter1_reg;
reg   [7:0] present_window_14_load_reg_2699_pp0_iter2_reg;
wire   [0:0] icmp_ln93_fu_503_p2;
reg   [0:0] icmp_ln93_reg_2712_pp0_iter1_reg;
reg   [0:0] icmp_ln93_reg_2712_pp0_iter2_reg;
wire   [8:0] present_window_14_cast6_fu_516_p1;
reg   [8:0] present_window_14_cast6_reg_2716;
wire   [10:0] add_ln123_3_fu_552_p2;
reg   [10:0] add_ln123_3_reg_2721;
wire   [1:0] trunc_ln111_fu_617_p1;
reg   [1:0] trunc_ln111_reg_2726;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
reg   [9:0] lshr_ln1_reg_2731;
reg   [7:0] present_window_15_load_reg_2736;
reg   [7:0] present_window_15_load_reg_2736_pp0_iter2_reg;
reg   [9:0] dict_addr_reg_2748;
reg   [9:0] dict_1_addr_reg_2753;
reg   [9:0] dict_2_addr_reg_2758;
reg   [9:0] dict_3_addr_reg_2763;
reg   [7:0] new_byte_reg_2768;
reg    ap_block_pp0_stage1_11001_grp1;
wire   [431:0] dictReadValue_reg_fu_668_p11;
reg   [431:0] dictReadValue_reg_reg_2779;
wire   [359:0] trunc_ln127_fu_691_p1;
reg   [359:0] trunc_ln127_reg_2825;
wire   [31:0] currIdx_reg_fu_700_p2;
reg   [31:0] currIdx_reg_reg_2830;
reg   [23:0] compareIdx_reg_2846;
wire   [1:0] len_2_fu_781_p3;
reg   [1:0] len_2_reg_2851;
wire   [0:0] done_2_fu_803_p2;
reg   [0:0] done_2_reg_2856;
wire   [1:0] len_3_fu_809_p2;
reg   [1:0] len_3_reg_2862;
wire   [0:0] icmp_ln168_2_fu_824_p2;
reg   [0:0] icmp_ln168_2_reg_2867;
wire   [0:0] icmp_ln168_3_fu_838_p2;
reg   [0:0] icmp_ln168_3_reg_2872;
wire   [0:0] icmp_ln168_4_fu_852_p2;
reg   [0:0] icmp_ln168_4_reg_2877;
reg   [23:0] compareIdx_1_reg_2882;
wire   [1:0] len_13_fu_918_p3;
reg   [1:0] len_13_reg_2887;
wire   [0:0] done_7_fu_940_p2;
reg   [0:0] done_7_reg_2892;
wire   [1:0] len_14_fu_946_p2;
reg   [1:0] len_14_reg_2898;
wire   [0:0] icmp_ln168_8_fu_961_p2;
reg   [0:0] icmp_ln168_8_reg_2903;
wire   [0:0] icmp_ln168_9_fu_975_p2;
reg   [0:0] icmp_ln168_9_reg_2908;
wire   [0:0] icmp_ln168_10_fu_989_p2;
reg   [0:0] icmp_ln168_10_reg_2913;
reg   [23:0] compareIdx_2_reg_2918;
wire   [0:0] len_22_fu_1012_p2;
reg   [0:0] len_22_reg_2923;
wire   [0:0] icmp_ln168_12_fu_1026_p2;
reg   [0:0] icmp_ln168_12_reg_2930;
wire   [0:0] icmp_ln168_13_fu_1040_p2;
reg   [0:0] icmp_ln168_13_reg_2935;
wire   [0:0] icmp_ln168_14_fu_1054_p2;
reg   [0:0] icmp_ln168_14_reg_2940;
wire   [0:0] icmp_ln168_15_fu_1068_p2;
reg   [0:0] icmp_ln168_15_reg_2945;
wire   [0:0] icmp_ln168_16_fu_1082_p2;
reg   [0:0] icmp_ln168_16_reg_2950;
reg    ap_block_pp0_stage2_11001_grp2;
reg   [23:0] compareIdx_3_reg_2955;
wire   [0:0] len_33_fu_1105_p2;
reg   [0:0] len_33_reg_2960;
wire   [0:0] icmp_ln168_18_fu_1119_p2;
reg   [0:0] icmp_ln168_18_reg_2967;
wire   [0:0] icmp_ln168_19_fu_1133_p2;
reg   [0:0] icmp_ln168_19_reg_2972;
wire   [0:0] icmp_ln168_20_fu_1147_p2;
reg   [0:0] icmp_ln168_20_reg_2977;
wire   [0:0] icmp_ln168_21_fu_1161_p2;
reg   [0:0] icmp_ln168_21_reg_2982;
wire   [0:0] icmp_ln168_22_fu_1175_p2;
reg   [0:0] icmp_ln168_22_reg_2987;
reg   [0:0] icmp_ln168_22_reg_2987_pp0_iter2_reg;
reg   [23:0] compareIdx_4_reg_2992;
wire   [0:0] len_44_fu_1198_p2;
reg   [0:0] len_44_reg_2997;
wire   [0:0] done_21_fu_1223_p2;
reg   [0:0] done_21_reg_3003;
wire   [0:0] icmp_ln168_25_fu_1238_p2;
reg   [0:0] icmp_ln168_25_reg_3009;
wire   [0:0] icmp_ln168_26_fu_1252_p2;
reg   [0:0] icmp_ln168_26_reg_3014;
wire   [0:0] icmp_ln168_27_fu_1266_p2;
reg   [0:0] icmp_ln168_27_reg_3019;
wire   [0:0] icmp_ln168_28_fu_1280_p2;
reg   [0:0] icmp_ln168_28_reg_3024;
reg   [23:0] compareIdx_5_reg_3029;
wire   [0:0] len_55_fu_1303_p2;
reg   [0:0] len_55_reg_3034;
wire   [0:0] icmp_ln168_30_fu_1317_p2;
reg   [0:0] icmp_ln168_30_reg_3041;
wire   [0:0] icmp_ln168_31_fu_1331_p2;
reg   [0:0] icmp_ln168_31_reg_3046;
wire   [0:0] icmp_ln168_32_fu_1345_p2;
reg   [0:0] icmp_ln168_32_reg_3051;
wire   [0:0] icmp_ln168_33_fu_1359_p2;
reg   [0:0] icmp_ln168_33_reg_3056;
reg   [0:0] icmp_ln168_33_reg_3056_pp0_iter2_reg;
wire   [0:0] icmp_ln168_34_fu_1373_p2;
reg   [0:0] icmp_ln168_34_reg_3061;
reg   [0:0] icmp_ln168_34_reg_3061_pp0_iter2_reg;
wire   [0:0] done_4_fu_1408_p2;
reg   [0:0] done_4_reg_3066;
wire   [2:0] len_8_fu_1419_p3;
reg   [2:0] len_8_reg_3071;
wire   [0:0] icmp_ln178_fu_1427_p2;
reg   [0:0] icmp_ln178_reg_3077;
wire   [0:0] icmp_ln179_fu_1447_p2;
reg   [0:0] icmp_ln179_reg_3082;
wire   [31:0] match_offset_fu_1453_p2;
reg   [31:0] match_offset_reg_3087;
wire   [0:0] done_9_fu_1489_p2;
reg   [0:0] done_9_reg_3094;
wire   [2:0] len_19_fu_1500_p3;
reg   [2:0] len_19_reg_3099;
wire   [0:0] icmp_ln178_1_fu_1508_p2;
reg   [0:0] icmp_ln178_1_reg_3105;
wire   [31:0] sub_ln179_1_fu_1513_p2;
reg   [31:0] sub_ln179_1_reg_3110;
wire   [0:0] icmp_ln179_1_fu_1528_p2;
reg   [0:0] icmp_ln179_1_reg_3115;
wire   [1:0] len_26_fu_1573_p3;
reg   [1:0] len_26_reg_3120;
wire   [0:0] done_13_fu_1581_p2;
reg   [0:0] done_13_reg_3125;
wire   [1:0] len_37_fu_1625_p3;
reg   [1:0] len_37_reg_3131;
wire   [0:0] done_18_fu_1633_p2;
reg   [0:0] done_18_reg_3136;
wire   [2:0] len_50_fu_1688_p3;
reg   [2:0] len_50_reg_3142;
wire   [0:0] done_24_fu_1696_p2;
reg   [0:0] done_24_reg_3148;
wire   [1:0] len_59_fu_1740_p3;
reg   [1:0] len_59_reg_3154;
wire   [0:0] done_28_fu_1748_p2;
reg   [0:0] done_28_reg_3159;
wire   [2:0] len_67_fu_1800_p3;
reg   [2:0] len_67_reg_3165;
wire   [31:0] match_offset_1_fu_1807_p2;
reg   [31:0] match_offset_1_reg_3172;
wire   [0:0] done_14_fu_1855_p2;
reg   [0:0] done_14_reg_3177;
wire   [2:0] len_30_fu_1865_p3;
reg   [2:0] len_30_reg_3182;
wire   [0:0] icmp_ln178_2_fu_1873_p2;
reg   [0:0] icmp_ln178_2_reg_3188;
wire   [0:0] icmp_ln179_2_fu_1893_p2;
reg   [0:0] icmp_ln179_2_reg_3193;
wire   [31:0] match_offset_2_fu_1899_p2;
reg   [31:0] match_offset_2_reg_3198;
wire   [2:0] len_39_fu_1917_p3;
reg   [2:0] len_39_reg_3205;
wire   [0:0] done_19_fu_1924_p2;
reg   [0:0] done_19_reg_3211;
wire   [0:0] icmp_ln178_3_fu_1928_p2;
reg   [0:0] icmp_ln178_3_reg_3217;
wire   [31:0] sub_ln179_3_fu_1933_p2;
reg   [31:0] sub_ln179_3_reg_3222;
wire   [0:0] icmp_ln179_3_fu_1948_p2;
reg   [0:0] icmp_ln179_3_reg_3227;
wire   [2:0] len_70_fu_1978_p3;
reg   [2:0] len_70_reg_3232;
wire   [0:0] icmp_ln178_4_fu_1986_p2;
reg   [0:0] icmp_ln178_4_reg_3240;
wire   [31:0] sub_ln179_4_fu_1991_p2;
reg   [31:0] sub_ln179_4_reg_3245;
wire   [0:0] icmp_ln179_4_fu_2006_p2;
reg   [0:0] icmp_ln179_4_reg_3250;
wire   [0:0] icmp_ln178_5_fu_2015_p2;
reg   [0:0] icmp_ln178_5_reg_3255;
wire   [31:0] sub_ln179_5_fu_2020_p2;
reg   [31:0] sub_ln179_5_reg_3260;
wire   [0:0] icmp_ln179_5_fu_2035_p2;
reg   [0:0] icmp_ln179_5_reg_3265;
wire   [0:0] and_ln191_fu_2065_p2;
reg   [0:0] and_ln191_reg_3270;
wire   [2:0] match_length_1_fu_2071_p3;
reg   [2:0] match_length_1_reg_3275;
wire   [0:0] and_ln191_10_fu_2084_p2;
reg   [0:0] and_ln191_10_reg_3281;
wire   [2:0] len_68_fu_2106_p3;
reg   [2:0] len_68_reg_3286;
wire   [2:0] len_41_fu_2148_p3;
reg   [2:0] len_41_reg_3291;
wire   [2:0] len_42_fu_2154_p2;
reg   [2:0] len_42_reg_3296;
wire   [31:0] match_offset_3_fu_2160_p2;
reg   [31:0] match_offset_3_reg_3301;
wire   [2:0] match_length_3_fu_2185_p3;
reg   [2:0] match_length_3_reg_3308;
wire   [0:0] and_ln191_2_fu_2219_p2;
reg   [0:0] and_ln191_2_reg_3313;
wire   [15:0] select_ln191_4_fu_2244_p3;
reg   [15:0] select_ln191_4_reg_3319;
wire   [31:0] match_offset_4_fu_2292_p2;
reg   [31:0] match_offset_4_reg_3324;
wire   [0:0] done_29_fu_2336_p2;
reg   [0:0] done_29_reg_3329;
wire   [2:0] len_63_fu_2346_p3;
reg   [2:0] len_63_reg_3334;
wire   [31:0] match_offset_5_fu_2354_p2;
reg   [31:0] match_offset_5_reg_3340;
wire   [0:0] and_ln191_3_fu_2392_p2;
reg   [0:0] and_ln191_3_reg_3347;
wire   [2:0] match_length_7_fu_2398_p3;
reg   [2:0] match_length_7_reg_3352;
wire   [0:0] and_ln191_22_fu_2411_p2;
reg   [0:0] and_ln191_22_reg_3358;
wire   [15:0] select_ln191_2_fu_2423_p3;
reg   [15:0] select_ln191_2_reg_3363;
wire   [2:0] len_71_fu_2447_p3;
reg   [2:0] len_71_reg_3368;
wire   [0:0] and_ln191_4_fu_2499_p2;
reg   [0:0] and_ln191_4_reg_3373;
wire   [2:0] match_length_9_fu_2504_p3;
reg   [2:0] match_length_9_reg_3378;
wire   [0:0] and_ln191_5_fu_2538_p2;
reg   [0:0] and_ln191_5_reg_3383;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln111_fu_634_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] i_fu_298;
wire   [31:0] i_2_fu_641_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg   [7:0] present_window_11_fu_302;
wire    ap_block_pp0_stage1_grp0;
reg   [7:0] present_window_12_fu_306;
reg   [7:0] present_window_13_fu_310;
reg   [7:0] present_window_14_fu_314;
reg   [7:0] present_window_15_fu_318;
reg    ap_block_pp0_stage2_01001_grp2;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage2_11001;
reg    ap_loop_exit_ready_pp0_iter2_reg;
wire    ap_block_pp0_stage2_01001_grp0;
reg    dict_ce0_local;
reg   [9:0] dict_address0_local;
reg    dict_we0_local;
wire   [431:0] dictWriteValue_fu_709_p9;
wire    ap_block_pp0_stage2_grp0;
reg    dict_1_ce0_local;
reg   [9:0] dict_1_address0_local;
reg    dict_1_we0_local;
reg    dict_2_ce0_local;
reg   [9:0] dict_2_address0_local;
reg    dict_2_we0_local;
reg    dict_3_ce0_local;
reg   [9:0] dict_3_address0_local;
reg    dict_3_we0_local;
wire   [8:0] factor_fu_520_p3;
wire   [8:0] zext_ln119_fu_512_p1;
wire   [8:0] add_ln123_fu_532_p2;
wire   [9:0] zext_ln123_1_fu_538_p1;
wire   [9:0] zext_ln123_fu_528_p1;
wire   [9:0] add_ln123_1_fu_542_p2;
wire   [10:0] zext_ln123_2_fu_548_p1;
wire   [10:0] zext_ln118_fu_508_p1;
wire   [10:0] shl_ln1_fu_565_p3;
wire   [8:0] zext_ln121_fu_576_p1;
wire   [8:0] tmp1_fu_579_p2;
wire   [10:0] tmp2_fu_584_p3;
wire   [11:0] shl_ln_fu_558_p3;
wire   [11:0] tmp19_cast_fu_592_p1;
wire   [11:0] zext_ln123_3_fu_602_p1;
wire   [11:0] zext_ln120_fu_572_p1;
wire   [11:0] add_ln123_4_fu_605_p2;
wire   [11:0] add_ln123_2_fu_596_p2;
wire   [11:0] add_ln123_5_fu_611_p2;
wire   [431:0] dictReadValue_reg_fu_668_p9;
wire   [23:0] trunc_ln132_fu_705_p1;
wire   [7:0] trunc_ln168_fu_735_p1;
wire   [0:0] len_fu_738_p2;
wire   [7:0] tmp_2_fu_753_p4;
wire   [0:0] icmp_ln168_fu_762_p2;
wire   [0:0] done_fu_747_p2;
wire   [0:0] done_1_fu_767_p2;
wire   [1:0] zext_ln168_fu_743_p1;
wire   [1:0] len_1_fu_773_p3;
wire   [7:0] tmp_3_fu_789_p4;
wire   [0:0] icmp_ln168_1_fu_798_p2;
wire   [7:0] tmp_4_fu_815_p4;
wire   [7:0] tmp_5_fu_829_p4;
wire   [7:0] tmp_6_fu_843_p4;
wire   [7:0] tmp_8_fu_866_p4;
wire   [0:0] len_11_fu_875_p2;
wire   [7:0] tmp_9_fu_890_p4;
wire   [0:0] icmp_ln168_6_fu_899_p2;
wire   [0:0] done_5_fu_884_p2;
wire   [0:0] done_6_fu_904_p2;
wire   [1:0] zext_ln168_1_fu_880_p1;
wire   [1:0] len_12_fu_910_p3;
wire   [7:0] tmp_s_fu_926_p4;
wire   [0:0] icmp_ln168_7_fu_935_p2;
wire   [7:0] tmp_7_fu_952_p4;
wire   [7:0] tmp_1_fu_966_p4;
wire   [7:0] tmp_10_fu_980_p4;
wire   [7:0] tmp_12_fu_1003_p4;
wire   [7:0] tmp_13_fu_1017_p4;
wire   [7:0] tmp_14_fu_1031_p4;
wire   [7:0] tmp_15_fu_1045_p4;
wire   [7:0] tmp_16_fu_1059_p4;
wire   [7:0] tmp_17_fu_1073_p4;
wire   [7:0] tmp_18_fu_1096_p4;
wire   [7:0] tmp_19_fu_1110_p4;
wire   [7:0] tmp_20_fu_1124_p4;
wire   [7:0] tmp_21_fu_1138_p4;
wire   [7:0] tmp_22_fu_1152_p4;
wire   [7:0] tmp_23_fu_1166_p4;
wire   [7:0] tmp_24_fu_1189_p4;
wire   [7:0] tmp_25_fu_1209_p4;
wire   [0:0] icmp_ln168_24_fu_1218_p2;
wire   [0:0] done_20_fu_1203_p2;
wire   [7:0] tmp_26_fu_1229_p4;
wire   [7:0] tmp_27_fu_1243_p4;
wire   [7:0] tmp_28_fu_1257_p4;
wire   [7:0] tmp_29_fu_1271_p4;
wire   [7:0] tmp_30_fu_1294_p4;
wire   [7:0] tmp_31_fu_1308_p4;
wire   [7:0] tmp_32_fu_1322_p4;
wire   [7:0] tmp_33_fu_1336_p4;
wire   [7:0] tmp_34_fu_1350_p4;
wire   [7:0] tmp_35_fu_1364_p4;
wire   [1:0] len_4_fu_1381_p3;
wire   [2:0] zext_ln165_fu_1386_p1;
wire   [0:0] done_3_fu_1390_p2;
wire   [2:0] len_5_fu_1394_p2;
wire   [2:0] len_6_fu_1400_p3;
wire   [2:0] len_7_fu_1413_p2;
wire   [31:0] zext_ln161_fu_1378_p1;
wire   [31:0] sub_ln179_fu_1432_p2;
wire   [15:0] tmp_fu_1437_p4;
wire   [1:0] len_15_fu_1462_p3;
wire   [2:0] zext_ln165_1_fu_1467_p1;
wire   [0:0] done_8_fu_1471_p2;
wire   [2:0] len_16_fu_1475_p2;
wire   [2:0] len_17_fu_1481_p3;
wire   [2:0] len_18_fu_1494_p2;
wire   [31:0] zext_ln161_1_fu_1459_p1;
wire   [15:0] tmp_36_fu_1518_p4;
wire   [0:0] done_10_fu_1537_p2;
wire   [0:0] done_11_fu_1542_p2;
wire   [1:0] zext_ln168_2_fu_1534_p1;
wire   [1:0] len_23_fu_1547_p3;
wire   [1:0] len_24_fu_1554_p3;
wire   [0:0] done_12_fu_1562_p2;
wire   [1:0] len_25_fu_1567_p2;
wire   [0:0] done_15_fu_1589_p2;
wire   [0:0] done_16_fu_1594_p2;
wire   [1:0] zext_ln168_3_fu_1586_p1;
wire   [1:0] len_34_fu_1599_p3;
wire   [1:0] len_35_fu_1606_p3;
wire   [0:0] done_17_fu_1614_p2;
wire   [1:0] len_36_fu_1619_p2;
wire   [1:0] zext_ln168_4_fu_1638_p1;
wire   [1:0] len_45_fu_1641_p3;
wire   [1:0] len_46_fu_1648_p3;
wire   [0:0] done_22_fu_1655_p2;
wire   [1:0] len_47_fu_1659_p2;
wire   [1:0] len_48_fu_1665_p3;
wire   [2:0] zext_ln165_4_fu_1673_p1;
wire   [0:0] done_23_fu_1677_p2;
wire   [2:0] len_49_fu_1682_p2;
wire   [0:0] done_25_fu_1704_p2;
wire   [0:0] done_26_fu_1709_p2;
wire   [1:0] zext_ln168_5_fu_1701_p1;
wire   [1:0] len_56_fu_1714_p3;
wire   [1:0] len_57_fu_1721_p3;
wire   [0:0] done_27_fu_1729_p2;
wire   [1:0] len_58_fu_1734_p2;
wire   [0:0] or_ln168_fu_1753_p2;
wire   [2:0] len_9_fu_1757_p2;
wire   [2:0] len_66_fu_1762_p3;
wire   [0:0] icmp_ln185_1_fu_1780_p2;
wire   [0:0] icmp_ln185_fu_1774_p2;
wire   [0:0] or_ln168_5_fu_1791_p2;
wire   [2:0] len_20_fu_1795_p2;
wire   [0:0] icmp_ln185_3_fu_1824_p2;
wire   [0:0] icmp_ln185_2_fu_1818_p2;
wire   [2:0] zext_ln165_2_fu_1839_p1;
wire   [2:0] len_27_fu_1842_p2;
wire   [2:0] len_28_fu_1848_p3;
wire   [2:0] len_29_fu_1859_p2;
wire   [31:0] zext_ln161_2_fu_1836_p1;
wire   [31:0] sub_ln179_2_fu_1878_p2;
wire   [15:0] tmp_38_fu_1883_p4;
wire   [2:0] zext_ln165_3_fu_1908_p1;
wire   [2:0] len_38_fu_1911_p2;
wire   [31:0] zext_ln161_3_fu_1905_p1;
wire   [15:0] tmp_40_fu_1938_p4;
wire   [2:0] len_51_fu_1957_p2;
wire   [2:0] len_52_fu_1962_p3;
wire   [0:0] or_ln168_20_fu_1968_p2;
wire   [2:0] len_53_fu_1972_p2;
wire   [31:0] zext_ln161_4_fu_1954_p1;
wire   [15:0] tmp_42_fu_1996_p4;
wire   [31:0] zext_ln161_5_fu_2012_p1;
wire   [15:0] tmp_44_fu_2025_p4;
wire   [0:0] or_ln185_fu_1785_p2;
wire   [0:0] and_ln191_6_fu_2041_p2;
wire   [0:0] icmp_ln180_fu_1769_p2;
wire   [0:0] tmp_45_fu_2052_p3;
wire   [0:0] and_ln191_8_fu_2060_p2;
wire   [0:0] and_ln191_7_fu_2046_p2;
wire   [0:0] or_ln185_1_fu_1830_p2;
wire   [0:0] and_ln191_9_fu_2079_p2;
wire   [0:0] icmp_ln180_1_fu_1812_p2;
wire   [0:0] or_ln168_10_fu_2097_p2;
wire   [2:0] len_31_fu_2101_p2;
wire   [0:0] icmp_ln185_5_fu_2132_p2;
wire   [0:0] icmp_ln185_4_fu_2126_p2;
wire   [2:0] len_40_fu_2143_p2;
wire   [0:0] tmp_11_fu_2090_p3;
wire   [0:0] icmp_ln191_fu_2165_p2;
wire   [0:0] and_ln191_11_fu_2169_p2;
wire   [0:0] and_ln191_12_fu_2175_p2;
wire   [0:0] and_ln191_1_fu_2180_p2;
wire   [0:0] or_ln185_2_fu_2137_p2;
wire   [0:0] and_ln191_13_fu_2197_p2;
wire   [0:0] icmp_ln180_2_fu_2121_p2;
wire   [0:0] tmp_37_fu_2113_p3;
wire   [0:0] icmp_ln191_1_fu_2191_p2;
wire   [0:0] and_ln191_15_fu_2208_p2;
wire   [0:0] and_ln191_16_fu_2214_p2;
wire   [0:0] and_ln191_14_fu_2202_p2;
wire   [15:0] trunc_ln191_fu_2225_p1;
wire   [15:0] trunc_ln191_1_fu_2228_p1;
wire   [0:0] or_ln191_2_fu_2239_p2;
wire   [15:0] select_ln191_fu_2231_p3;
wire   [0:0] or_ln168_15_fu_2252_p2;
wire   [2:0] len_69_fu_2256_p3;
wire   [0:0] icmp_ln185_7_fu_2281_p2;
wire   [0:0] icmp_ln185_6_fu_2275_p2;
wire   [0:0] icmp_ln185_9_fu_2308_p2;
wire   [0:0] icmp_ln185_8_fu_2303_p2;
wire   [2:0] zext_ln165_5_fu_2320_p1;
wire   [2:0] len_60_fu_2323_p2;
wire   [2:0] len_61_fu_2329_p3;
wire   [2:0] len_62_fu_2340_p2;
wire   [2:0] match_length_5_fu_2359_p3;
wire   [0:0] or_ln185_3_fu_2286_p2;
wire   [0:0] and_ln191_17_fu_2370_p2;
wire   [0:0] icmp_ln180_3_fu_2270_p2;
wire   [0:0] tmp_39_fu_2262_p3;
wire   [0:0] icmp_ln191_2_fu_2364_p2;
wire   [0:0] and_ln191_19_fu_2381_p2;
wire   [0:0] and_ln191_20_fu_2387_p2;
wire   [0:0] and_ln191_18_fu_2375_p2;
wire   [0:0] or_ln185_4_fu_2314_p2;
wire   [0:0] and_ln191_21_fu_2406_p2;
wire   [0:0] icmp_ln180_4_fu_2297_p2;
wire   [15:0] trunc_ln191_4_fu_2417_p1;
wire   [15:0] trunc_ln191_5_fu_2420_p1;
wire   [0:0] or_ln168_25_fu_2438_p2;
wire   [2:0] len_64_fu_2442_p2;
wire   [0:0] icmp_ln185_11_fu_2473_p2;
wire   [0:0] icmp_ln185_10_fu_2467_p2;
wire   [0:0] tmp_41_fu_2431_p3;
wire   [0:0] icmp_ln191_3_fu_2484_p2;
wire   [0:0] and_ln191_23_fu_2488_p2;
wire   [0:0] and_ln191_24_fu_2494_p2;
wire   [0:0] or_ln185_5_fu_2478_p2;
wire   [0:0] and_ln191_25_fu_2516_p2;
wire   [0:0] icmp_ln180_5_fu_2462_p2;
wire   [0:0] tmp_43_fu_2454_p3;
wire   [0:0] icmp_ln191_4_fu_2510_p2;
wire   [0:0] and_ln191_27_fu_2527_p2;
wire   [0:0] and_ln191_28_fu_2533_p2;
wire   [0:0] and_ln191_26_fu_2521_p2;
wire   [15:0] trunc_ln191_2_fu_2552_p1;
wire   [15:0] trunc_ln191_3_fu_2555_p1;
wire   [0:0] or_ln191_fu_2544_p2;
wire   [15:0] select_ln191_1_fu_2558_p3;
wire   [0:0] or_ln191_1_fu_2548_p2;
wire   [0:0] or_ln191_3_fu_2572_p2;
wire   [15:0] select_ln191_3_fu_2565_p3;
wire   [2:0] match_length_11_fu_2585_p3;
wire   [15:0] select_ln191_5_fu_2578_p3;
wire   [7:0] zext_ln148_fu_2590_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to3;
reg    ap_done_pending_pp0;
reg    ap_block_pp0;
reg    ap_predicate_op77_load_state4;
reg    ap_enable_operation_77;
reg    ap_enable_state4_pp0_iter1_stage0;
reg    ap_predicate_op89_load_state5;
reg    ap_enable_operation_89;
reg    ap_enable_state5_pp0_iter1_stage1;
reg    ap_predicate_op105_store_state6;
reg    ap_enable_operation_105;
reg    ap_enable_state6_pp0_iter1_stage2;
reg    ap_predicate_op78_load_state4;
reg    ap_enable_operation_78;
reg    ap_predicate_op90_load_state5;
reg    ap_enable_operation_90;
reg    ap_predicate_op103_store_state6;
reg    ap_enable_operation_103;
reg    ap_predicate_op79_load_state4;
reg    ap_enable_operation_79;
reg    ap_predicate_op91_load_state5;
reg    ap_enable_operation_91;
reg    ap_predicate_op101_store_state6;
reg    ap_enable_operation_101;
reg    ap_predicate_op80_load_state4;
reg    ap_enable_operation_80;
reg    ap_predicate_op92_load_state5;
reg    ap_enable_operation_92;
reg    ap_predicate_op107_store_state6;
reg    ap_enable_operation_107;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] dictReadValue_reg_fu_668_p1;
wire   [1:0] dictReadValue_reg_fu_668_p3;
wire  signed [1:0] dictReadValue_reg_fu_668_p5;
wire  signed [1:0] dictReadValue_reg_fu_668_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 i_fu_298 = 32'd0;
#0 present_window_11_fu_302 = 8'd0;
#0 present_window_12_fu_306 = 8'd0;
#0 present_window_13_fu_310 = 8'd0;
#0 present_window_14_fu_314 = 8'd0;
#0 present_window_15_fu_318 = 8'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) lz4CompressEngineRun_sparsemux_9_2_432_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 432 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 432 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 432 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 432 ),
    .def_WIDTH( 432 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 432 ))
sparsemux_9_2_432_1_1_U16(
    .din0(dict_q0),
    .din1(dict_1_q0),
    .din2(dict_2_q0),
    .din3(dict_3_q0),
    .def(dictReadValue_reg_fu_668_p9),
    .sel(trunc_ln111_reg_2726),
    .dout(dictReadValue_reg_fu_668_p11)
);

lz4CompressEngineRun_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_298 <= 32'd5;
        end else if (((icmp_ln93_reg_2712 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_298 <= i_2_fu_641_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            present_window_11_fu_302 <= arrayidx54_promoted168_reload;
        end else if (((icmp_ln93_reg_2712 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            present_window_11_fu_302 <= present_window_12_load_reg_2671;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            present_window_12_fu_306 <= arrayidx61_promoted170_reload;
        end else if (((icmp_ln93_reg_2712 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            present_window_12_fu_306 <= present_window_13_load_reg_2685;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            present_window_13_fu_310 <= arrayidx71_promoted172_reload;
        end else if (((icmp_ln93_reg_2712 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            present_window_13_fu_310 <= present_window_14_load_reg_2699;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            present_window_14_fu_314 <= arrayidx42_3_promoted174_reload;
        end else if (((icmp_ln93_reg_2712 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            present_window_14_fu_314 <= present_window_15_fu_318;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        present_window_15_fu_318 <= arrayidx48_promoted176_reload;
    end else if (((icmp_ln93_reg_2712 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        present_window_15_fu_318 <= inStream_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln123_3_reg_2721 <= add_ln123_3_fu_552_p2;
        and_ln191_10_reg_3281 <= and_ln191_10_fu_2084_p2;
        and_ln191_4_reg_3373 <= and_ln191_4_fu_2499_p2;
        and_ln191_5_reg_3383 <= and_ln191_5_fu_2538_p2;
        and_ln191_reg_3270 <= and_ln191_fu_2065_p2;
        dictReadValue_reg_reg_2779 <= dictReadValue_reg_fu_668_p11;
        done_14_reg_3177 <= done_14_fu_1855_p2;
        done_19_reg_3211 <= done_19_fu_1924_p2;
        icmp_ln178_2_reg_3188 <= icmp_ln178_2_fu_1873_p2;
        icmp_ln178_3_reg_3217 <= icmp_ln178_3_fu_1928_p2;
        icmp_ln178_4_reg_3240 <= icmp_ln178_4_fu_1986_p2;
        icmp_ln178_5_reg_3255 <= icmp_ln178_5_fu_2015_p2;
        icmp_ln179_2_reg_3193 <= icmp_ln179_2_fu_1893_p2;
        icmp_ln179_3_reg_3227 <= icmp_ln179_3_fu_1948_p2;
        icmp_ln179_4_reg_3250 <= icmp_ln179_4_fu_2006_p2;
        icmp_ln179_5_reg_3265 <= icmp_ln179_5_fu_2035_p2;
        len_30_reg_3182 <= len_30_fu_1865_p3;
        len_39_reg_3205 <= len_39_fu_1917_p3;
        len_67_reg_3165 <= len_67_fu_1800_p3;
        len_70_reg_3232 <= len_70_fu_1978_p3;
        len_71_reg_3368 <= len_71_fu_2447_p3;
        match_length_1_reg_3275 <= match_length_1_fu_2071_p3;
        match_length_9_reg_3378 <= match_length_9_fu_2504_p3;
        match_offset_1_reg_3172 <= match_offset_1_fu_1807_p2;
        match_offset_2_reg_3198 <= match_offset_2_fu_1899_p2;
        present_window_11_load_reg_2657_pp0_iter1_reg <= present_window_11_load_reg_2657;
        present_window_11_load_reg_2657_pp0_iter2_reg <= present_window_11_load_reg_2657_pp0_iter1_reg;
        present_window_11_load_reg_2657_pp0_iter3_reg <= present_window_11_load_reg_2657_pp0_iter2_reg;
        present_window_12_load_reg_2671_pp0_iter1_reg <= present_window_12_load_reg_2671;
        present_window_12_load_reg_2671_pp0_iter2_reg <= present_window_12_load_reg_2671_pp0_iter1_reg;
        present_window_13_load_reg_2685_pp0_iter1_reg <= present_window_13_load_reg_2685;
        present_window_13_load_reg_2685_pp0_iter2_reg <= present_window_13_load_reg_2685_pp0_iter1_reg;
        present_window_14_cast6_reg_2716[7 : 0] <= present_window_14_cast6_fu_516_p1[7 : 0];
        present_window_14_load_reg_2699_pp0_iter1_reg <= present_window_14_load_reg_2699;
        present_window_14_load_reg_2699_pp0_iter2_reg <= present_window_14_load_reg_2699_pp0_iter1_reg;
        sub_ln179_3_reg_3222 <= sub_ln179_3_fu_1933_p2;
        sub_ln179_4_reg_3245 <= sub_ln179_4_fu_1991_p2;
        sub_ln179_5_reg_3260 <= sub_ln179_5_fu_2020_p2;
        trunc_ln127_reg_2825 <= trunc_ln127_fu_691_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln191_22_reg_3358 <= and_ln191_22_fu_2411_p2;
        and_ln191_3_reg_3347 <= and_ln191_3_fu_2392_p2;
        dict_1_addr_reg_2753 <= zext_ln111_fu_634_p1;
        dict_2_addr_reg_2758 <= zext_ln111_fu_634_p1;
        dict_3_addr_reg_2763 <= zext_ln111_fu_634_p1;
        dict_addr_reg_2748 <= zext_ln111_fu_634_p1;
        done_13_reg_3125 <= done_13_fu_1581_p2;
        done_18_reg_3136 <= done_18_fu_1633_p2;
        done_24_reg_3148 <= done_24_fu_1696_p2;
        done_28_reg_3159 <= done_28_fu_1748_p2;
        done_29_reg_3329 <= done_29_fu_2336_p2;
        done_4_reg_3066 <= done_4_fu_1408_p2;
        done_9_reg_3094 <= done_9_fu_1489_p2;
        icmp_ln178_1_reg_3105 <= icmp_ln178_1_fu_1508_p2;
        icmp_ln178_reg_3077 <= icmp_ln178_fu_1427_p2;
        icmp_ln179_1_reg_3115 <= icmp_ln179_1_fu_1528_p2;
        icmp_ln179_reg_3082 <= icmp_ln179_fu_1447_p2;
        len_19_reg_3099 <= len_19_fu_1500_p3;
        len_26_reg_3120 <= len_26_fu_1573_p3;
        len_37_reg_3131 <= len_37_fu_1625_p3;
        len_50_reg_3142 <= len_50_fu_1688_p3;
        len_59_reg_3154 <= len_59_fu_1740_p3;
        len_63_reg_3334 <= len_63_fu_2346_p3;
        len_8_reg_3071 <= len_8_fu_1419_p3;
        match_length_7_reg_3352 <= match_length_7_fu_2398_p3;
        match_offset_4_reg_3324 <= match_offset_4_fu_2292_p2;
        match_offset_5_reg_3340 <= match_offset_5_fu_2354_p2;
        match_offset_reg_3087 <= match_offset_fu_1453_p2;
        present_window_15_load_reg_2736_pp0_iter2_reg <= present_window_15_load_reg_2736;
        select_ln191_2_reg_3363 <= select_ln191_2_fu_2423_p3;
        sub_ln179_1_reg_3110 <= sub_ln179_1_fu_1513_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        and_ln191_2_reg_3313 <= and_ln191_2_fu_2219_p2;
        icmp_ln168_16_reg_2950 <= icmp_ln168_16_fu_1082_p2;
        len_68_reg_3286 <= len_68_fu_2106_p3;
        match_length_3_reg_3308 <= match_length_3_fu_2185_p3;
        select_ln191_4_reg_3319 <= select_ln191_4_fu_2244_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        compareIdx_1_reg_2882 <= {{dictReadValue_reg_reg_2779[143:120]}};
        compareIdx_2_reg_2918 <= {{dictReadValue_reg_reg_2779[215:192]}};
        compareIdx_3_reg_2955 <= {{dictReadValue_reg_reg_2779[287:264]}};
        compareIdx_4_reg_2992 <= {{dictReadValue_reg_reg_2779[359:336]}};
        compareIdx_5_reg_3029 <= {{dictReadValue_reg_reg_2779[431:408]}};
        compareIdx_reg_2846 <= {{dictReadValue_reg_reg_2779[71:48]}};
        currIdx_reg_reg_2830 <= currIdx_reg_fu_700_p2;
        done_21_reg_3003 <= done_21_fu_1223_p2;
        done_2_reg_2856 <= done_2_fu_803_p2;
        done_7_reg_2892 <= done_7_fu_940_p2;
        icmp_ln168_10_reg_2913 <= icmp_ln168_10_fu_989_p2;
        icmp_ln168_12_reg_2930 <= icmp_ln168_12_fu_1026_p2;
        icmp_ln168_13_reg_2935 <= icmp_ln168_13_fu_1040_p2;
        icmp_ln168_14_reg_2940 <= icmp_ln168_14_fu_1054_p2;
        icmp_ln168_15_reg_2945 <= icmp_ln168_15_fu_1068_p2;
        icmp_ln168_18_reg_2967 <= icmp_ln168_18_fu_1119_p2;
        icmp_ln168_19_reg_2972 <= icmp_ln168_19_fu_1133_p2;
        icmp_ln168_20_reg_2977 <= icmp_ln168_20_fu_1147_p2;
        icmp_ln168_21_reg_2982 <= icmp_ln168_21_fu_1161_p2;
        icmp_ln168_22_reg_2987 <= icmp_ln168_22_fu_1175_p2;
        icmp_ln168_22_reg_2987_pp0_iter2_reg <= icmp_ln168_22_reg_2987;
        icmp_ln168_25_reg_3009 <= icmp_ln168_25_fu_1238_p2;
        icmp_ln168_26_reg_3014 <= icmp_ln168_26_fu_1252_p2;
        icmp_ln168_27_reg_3019 <= icmp_ln168_27_fu_1266_p2;
        icmp_ln168_28_reg_3024 <= icmp_ln168_28_fu_1280_p2;
        icmp_ln168_2_reg_2867 <= icmp_ln168_2_fu_824_p2;
        icmp_ln168_30_reg_3041 <= icmp_ln168_30_fu_1317_p2;
        icmp_ln168_31_reg_3046 <= icmp_ln168_31_fu_1331_p2;
        icmp_ln168_32_reg_3051 <= icmp_ln168_32_fu_1345_p2;
        icmp_ln168_33_reg_3056 <= icmp_ln168_33_fu_1359_p2;
        icmp_ln168_33_reg_3056_pp0_iter2_reg <= icmp_ln168_33_reg_3056;
        icmp_ln168_34_reg_3061 <= icmp_ln168_34_fu_1373_p2;
        icmp_ln168_34_reg_3061_pp0_iter2_reg <= icmp_ln168_34_reg_3061;
        icmp_ln168_3_reg_2872 <= icmp_ln168_3_fu_838_p2;
        icmp_ln168_4_reg_2877 <= icmp_ln168_4_fu_852_p2;
        icmp_ln168_8_reg_2903 <= icmp_ln168_8_fu_961_p2;
        icmp_ln168_9_reg_2908 <= icmp_ln168_9_fu_975_p2;
        len_13_reg_2887 <= len_13_fu_918_p3;
        len_14_reg_2898 <= len_14_fu_946_p2;
        len_22_reg_2923 <= len_22_fu_1012_p2;
        len_2_reg_2851 <= len_2_fu_781_p3;
        len_33_reg_2960 <= len_33_fu_1105_p2;
        len_3_reg_2862 <= len_3_fu_809_p2;
        len_41_reg_3291 <= len_41_fu_2148_p3;
        len_42_reg_3296 <= len_42_fu_2154_p2;
        len_44_reg_2997 <= len_44_fu_1198_p2;
        len_55_reg_3034 <= len_55_fu_1303_p2;
        lshr_ln1_reg_2731 <= {{add_ln123_5_fu_611_p2[11:2]}};
        match_offset_3_reg_3301 <= match_offset_3_fu_2160_p2;
        trunc_ln111_reg_2726 <= trunc_ln111_fu_617_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_1_reg_2651 <= i_fu_298;
        i_1_reg_2651_pp0_iter1_reg <= i_1_reg_2651;
        icmp_ln93_reg_2712 <= icmp_ln93_fu_503_p2;
        icmp_ln93_reg_2712_pp0_iter1_reg <= icmp_ln93_reg_2712;
        icmp_ln93_reg_2712_pp0_iter2_reg <= icmp_ln93_reg_2712_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        new_byte_reg_2768 <= inStream_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        present_window_11_load_reg_2657 <= present_window_11_fu_302;
        present_window_12_load_reg_2671 <= present_window_12_fu_306;
        present_window_13_load_reg_2685 <= present_window_13_fu_310;
        present_window_14_load_reg_2699 <= present_window_14_fu_314;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        present_window_15_load_reg_2736 <= present_window_15_fu_318;
    end
end

always @ (*) begin
    if (((icmp_ln93_reg_2712 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_reg_2712 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_grp2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        compressdStream_blk_n = compressdStream_full_n;
    end else begin
        compressdStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001_grp2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        compressdStream_write = 1'b1;
    end else begin
        compressdStream_write = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            dict_1_address0_local = dict_1_addr_reg_2753;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dict_1_address0_local = zext_ln111_fu_634_p1;
        end else begin
            dict_1_address0_local = 'bx;
        end
    end else begin
        dict_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        dict_1_ce0_local = 1'b1;
    end else begin
        dict_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln111_reg_2726 == 2'd1) & (icmp_ln93_reg_2712_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dict_1_we0_local = 1'b1;
    end else begin
        dict_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            dict_2_address0_local = dict_2_addr_reg_2758;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dict_2_address0_local = zext_ln111_fu_634_p1;
        end else begin
            dict_2_address0_local = 'bx;
        end
    end else begin
        dict_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        dict_2_ce0_local = 1'b1;
    end else begin
        dict_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln111_reg_2726 == 2'd2) & (icmp_ln93_reg_2712_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dict_2_we0_local = 1'b1;
    end else begin
        dict_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            dict_3_address0_local = dict_3_addr_reg_2763;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dict_3_address0_local = zext_ln111_fu_634_p1;
        end else begin
            dict_3_address0_local = 'bx;
        end
    end else begin
        dict_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        dict_3_ce0_local = 1'b1;
    end else begin
        dict_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln111_reg_2726 == 2'd3) & (icmp_ln93_reg_2712_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dict_3_we0_local = 1'b1;
    end else begin
        dict_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            dict_address0_local = dict_addr_reg_2748;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dict_address0_local = zext_ln111_fu_634_p1;
        end else begin
            dict_address0_local = 'bx;
        end
    end else begin
        dict_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        dict_ce0_local = 1'b1;
    end else begin
        dict_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln111_reg_2726 == 2'd0) & (icmp_ln93_reg_2712_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dict_we0_local = 1'b1;
    end else begin
        dict_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_reg_2712 == 1'd1) & (1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        inStream_blk_n = inStream_empty_n;
    end else begin
        inStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln93_reg_2712 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        inStream_read = 1'b1;
    end else begin
        inStream_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln93_reg_2712_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        present_window_11_out_ap_vld = 1'b1;
    end else begin
        present_window_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln93_reg_2712_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        present_window_12_out_ap_vld = 1'b1;
    end else begin
        present_window_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln93_reg_2712_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        present_window_13_out_ap_vld = 1'b1;
    end else begin
        present_window_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln93_reg_2712_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        present_window_14_out_ap_vld = 1'b1;
    end else begin
        present_window_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln93_reg_2712_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        present_window_15_out_ap_vld = 1'b1;
    end else begin
        present_window_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln123_1_fu_542_p2 = (zext_ln123_1_fu_538_p1 + zext_ln123_fu_528_p1);

assign add_ln123_2_fu_596_p2 = (shl_ln_fu_558_p3 + tmp19_cast_fu_592_p1);

assign add_ln123_3_fu_552_p2 = (zext_ln123_2_fu_548_p1 + zext_ln118_fu_508_p1);

assign add_ln123_4_fu_605_p2 = (zext_ln123_3_fu_602_p1 + zext_ln120_fu_572_p1);

assign add_ln123_5_fu_611_p2 = (add_ln123_4_fu_605_p2 + add_ln123_2_fu_596_p2);

assign add_ln123_fu_532_p2 = (zext_ln119_fu_512_p1 + present_window_14_cast6_fu_516_p1);

assign and_ln191_10_fu_2084_p2 = (icmp_ln180_1_fu_1812_p2 & and_ln191_9_fu_2079_p2);

assign and_ln191_11_fu_2169_p2 = (tmp_11_fu_2090_p3 & icmp_ln191_fu_2165_p2);

assign and_ln191_12_fu_2175_p2 = (icmp_ln178_1_reg_3105 & and_ln191_11_fu_2169_p2);

assign and_ln191_13_fu_2197_p2 = (or_ln185_2_fu_2137_p2 & icmp_ln179_2_reg_3193);

assign and_ln191_14_fu_2202_p2 = (icmp_ln180_2_fu_2121_p2 & and_ln191_13_fu_2197_p2);

assign and_ln191_15_fu_2208_p2 = (tmp_37_fu_2113_p3 & icmp_ln191_1_fu_2191_p2);

assign and_ln191_16_fu_2214_p2 = (icmp_ln178_2_reg_3188 & and_ln191_15_fu_2208_p2);

assign and_ln191_17_fu_2370_p2 = (or_ln185_3_fu_2286_p2 & icmp_ln179_3_reg_3227);

assign and_ln191_18_fu_2375_p2 = (icmp_ln180_3_fu_2270_p2 & and_ln191_17_fu_2370_p2);

assign and_ln191_19_fu_2381_p2 = (tmp_39_fu_2262_p3 & icmp_ln191_2_fu_2364_p2);

assign and_ln191_1_fu_2180_p2 = (and_ln191_12_fu_2175_p2 & and_ln191_10_reg_3281);

assign and_ln191_20_fu_2387_p2 = (icmp_ln178_3_reg_3217 & and_ln191_19_fu_2381_p2);

assign and_ln191_21_fu_2406_p2 = (or_ln185_4_fu_2314_p2 & icmp_ln179_4_reg_3250);

assign and_ln191_22_fu_2411_p2 = (icmp_ln180_4_fu_2297_p2 & and_ln191_21_fu_2406_p2);

assign and_ln191_23_fu_2488_p2 = (tmp_41_fu_2431_p3 & icmp_ln191_3_fu_2484_p2);

assign and_ln191_24_fu_2494_p2 = (icmp_ln178_4_reg_3240 & and_ln191_23_fu_2488_p2);

assign and_ln191_25_fu_2516_p2 = (or_ln185_5_fu_2478_p2 & icmp_ln179_5_reg_3265);

assign and_ln191_26_fu_2521_p2 = (icmp_ln180_5_fu_2462_p2 & and_ln191_25_fu_2516_p2);

assign and_ln191_27_fu_2527_p2 = (tmp_43_fu_2454_p3 & icmp_ln191_4_fu_2510_p2);

assign and_ln191_28_fu_2533_p2 = (icmp_ln178_5_reg_3255 & and_ln191_27_fu_2527_p2);

assign and_ln191_2_fu_2219_p2 = (and_ln191_16_fu_2214_p2 & and_ln191_14_fu_2202_p2);

assign and_ln191_3_fu_2392_p2 = (and_ln191_20_fu_2387_p2 & and_ln191_18_fu_2375_p2);

assign and_ln191_4_fu_2499_p2 = (and_ln191_24_fu_2494_p2 & and_ln191_22_reg_3358);

assign and_ln191_5_fu_2538_p2 = (and_ln191_28_fu_2533_p2 & and_ln191_26_fu_2521_p2);

assign and_ln191_6_fu_2041_p2 = (or_ln185_fu_1785_p2 & icmp_ln179_reg_3082);

assign and_ln191_7_fu_2046_p2 = (icmp_ln180_fu_1769_p2 & and_ln191_6_fu_2041_p2);

assign and_ln191_8_fu_2060_p2 = (tmp_45_fu_2052_p3 & icmp_ln178_reg_3077);

assign and_ln191_9_fu_2079_p2 = (or_ln185_1_fu_1830_p2 & icmp_ln179_1_reg_3115);

assign and_ln191_fu_2065_p2 = (and_ln191_8_fu_2060_p2 & and_ln191_7_fu_2046_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_pp0 = (((ap_ST_fsm_pp0_stage2 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage2_subdone)) | ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone)) | ((ap_ST_fsm_pp0_stage1 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage1_subdone)));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage1_iter1_grp1));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage1_iter1_grp1));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage1_iter1_grp1));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_01001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001_grp2 = ((compressdStream_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((compressdStream_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp2 = ((compressdStream_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((compressdStream_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage1_iter1_grp1 = ((icmp_ln93_reg_2712 == 1'd1) & (inStream_empty_n == 1'b0));
end

assign ap_done = ap_done_sig;

always @ (*) begin
    ap_enable_operation_101 = (ap_predicate_op101_store_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_103 = (ap_predicate_op103_store_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_105 = (ap_predicate_op105_store_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_107 = (ap_predicate_op107_store_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_77 = (ap_predicate_op77_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_78 = (ap_predicate_op78_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_79 = (ap_predicate_op79_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_80 = (ap_predicate_op80_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_89 = (ap_predicate_op89_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_90 = (ap_predicate_op90_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_91 = (ap_predicate_op91_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_92 = (ap_predicate_op92_load_state5 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state4_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state5_pp0_iter1_stage1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_enable_state6_pp0_iter1_stage2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

always @ (*) begin
    ap_predicate_op101_store_state6 = ((trunc_ln111_reg_2726 == 2'd2) & (icmp_ln93_reg_2712_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op103_store_state6 = ((trunc_ln111_reg_2726 == 2'd1) & (icmp_ln93_reg_2712_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op105_store_state6 = ((trunc_ln111_reg_2726 == 2'd0) & (icmp_ln93_reg_2712_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op107_store_state6 = ((trunc_ln111_reg_2726 == 2'd3) & (icmp_ln93_reg_2712_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op77_load_state4 = ((icmp_ln93_reg_2712 == 1'd1) & (trunc_ln111_reg_2726 == 2'd0));
end

always @ (*) begin
    ap_predicate_op78_load_state4 = ((icmp_ln93_reg_2712 == 1'd1) & (trunc_ln111_reg_2726 == 2'd1));
end

always @ (*) begin
    ap_predicate_op79_load_state4 = ((icmp_ln93_reg_2712 == 1'd1) & (trunc_ln111_reg_2726 == 2'd2));
end

always @ (*) begin
    ap_predicate_op80_load_state4 = ((icmp_ln93_reg_2712 == 1'd1) & (trunc_ln111_reg_2726 == 2'd3));
end

always @ (*) begin
    ap_predicate_op89_load_state5 = ((icmp_ln93_reg_2712 == 1'd1) & (trunc_ln111_reg_2726 == 2'd0));
end

always @ (*) begin
    ap_predicate_op90_load_state5 = ((icmp_ln93_reg_2712 == 1'd1) & (trunc_ln111_reg_2726 == 2'd1));
end

always @ (*) begin
    ap_predicate_op91_load_state5 = ((icmp_ln93_reg_2712 == 1'd1) & (trunc_ln111_reg_2726 == 2'd2));
end

always @ (*) begin
    ap_predicate_op92_load_state5 = ((icmp_ln93_reg_2712 == 1'd1) & (trunc_ln111_reg_2726 == 2'd3));
end

assign ap_ready = ap_ready_sig;

assign compressdStream_din = {{{select_ln191_5_fu_2578_p3}, {zext_ln148_fu_2590_p1}}, {present_window_11_load_reg_2657_pp0_iter3_reg}};

assign currIdx_reg_fu_700_p2 = ($signed(i_1_reg_2651_pp0_iter1_reg) + $signed(32'd4294967291));

assign dictReadValue_reg_fu_668_p9 = 'bx;

assign dictWriteValue_fu_709_p9 = {{{{{{{{trunc_ln127_reg_2825}, {trunc_ln132_fu_705_p1}}, {new_byte_reg_2768}}, {present_window_15_load_reg_2736}}, {present_window_14_load_reg_2699_pp0_iter1_reg}}, {present_window_13_load_reg_2685_pp0_iter1_reg}}, {present_window_12_load_reg_2671_pp0_iter1_reg}}, {present_window_11_load_reg_2657_pp0_iter1_reg}};

assign dict_1_address0 = dict_1_address0_local;

assign dict_1_ce0 = dict_1_ce0_local;

assign dict_1_d0 = dictWriteValue_fu_709_p9;

assign dict_1_we0 = dict_1_we0_local;

assign dict_2_address0 = dict_2_address0_local;

assign dict_2_ce0 = dict_2_ce0_local;

assign dict_2_d0 = dictWriteValue_fu_709_p9;

assign dict_2_we0 = dict_2_we0_local;

assign dict_3_address0 = dict_3_address0_local;

assign dict_3_ce0 = dict_3_ce0_local;

assign dict_3_d0 = dictWriteValue_fu_709_p9;

assign dict_3_we0 = dict_3_we0_local;

assign dict_address0 = dict_address0_local;

assign dict_ce0 = dict_ce0_local;

assign dict_d0 = dictWriteValue_fu_709_p9;

assign dict_we0 = dict_we0_local;

assign done_10_fu_1537_p2 = (len_22_reg_2923 ^ 1'd1);

assign done_11_fu_1542_p2 = (icmp_ln168_12_reg_2930 | done_10_fu_1537_p2);

assign done_12_fu_1562_p2 = (icmp_ln168_13_reg_2935 | done_11_fu_1542_p2);

assign done_13_fu_1581_p2 = (icmp_ln168_14_reg_2940 | done_12_fu_1562_p2);

assign done_14_fu_1855_p2 = (icmp_ln168_15_reg_2945 | done_13_reg_3125);

assign done_15_fu_1589_p2 = (len_33_reg_2960 ^ 1'd1);

assign done_16_fu_1594_p2 = (icmp_ln168_18_reg_2967 | done_15_fu_1589_p2);

assign done_17_fu_1614_p2 = (icmp_ln168_19_reg_2972 | done_16_fu_1594_p2);

assign done_18_fu_1633_p2 = (icmp_ln168_20_reg_2977 | done_17_fu_1614_p2);

assign done_19_fu_1924_p2 = (icmp_ln168_21_reg_2982 | done_18_reg_3136);

assign done_1_fu_767_p2 = (icmp_ln168_fu_762_p2 | done_fu_747_p2);

assign done_20_fu_1203_p2 = (len_44_fu_1198_p2 ^ 1'd1);

assign done_21_fu_1223_p2 = (icmp_ln168_24_fu_1218_p2 | done_20_fu_1203_p2);

assign done_22_fu_1655_p2 = (icmp_ln168_25_reg_3009 | done_21_reg_3003);

assign done_23_fu_1677_p2 = (icmp_ln168_26_reg_3014 | done_22_fu_1655_p2);

assign done_24_fu_1696_p2 = (icmp_ln168_27_reg_3019 | done_23_fu_1677_p2);

assign done_25_fu_1704_p2 = (len_55_reg_3034 ^ 1'd1);

assign done_26_fu_1709_p2 = (icmp_ln168_30_reg_3041 | done_25_fu_1704_p2);

assign done_27_fu_1729_p2 = (icmp_ln168_31_reg_3046 | done_26_fu_1709_p2);

assign done_28_fu_1748_p2 = (icmp_ln168_32_reg_3051 | done_27_fu_1729_p2);

assign done_29_fu_2336_p2 = (icmp_ln168_33_reg_3056_pp0_iter2_reg | done_28_reg_3159);

assign done_2_fu_803_p2 = (icmp_ln168_1_fu_798_p2 | done_1_fu_767_p2);

assign done_3_fu_1390_p2 = (icmp_ln168_2_reg_2867 | done_2_reg_2856);

assign done_4_fu_1408_p2 = (icmp_ln168_3_reg_2872 | done_3_fu_1390_p2);

assign done_5_fu_884_p2 = (len_11_fu_875_p2 ^ 1'd1);

assign done_6_fu_904_p2 = (icmp_ln168_6_fu_899_p2 | done_5_fu_884_p2);

assign done_7_fu_940_p2 = (icmp_ln168_7_fu_935_p2 | done_6_fu_904_p2);

assign done_8_fu_1471_p2 = (icmp_ln168_8_reg_2903 | done_7_reg_2892);

assign done_9_fu_1489_p2 = (icmp_ln168_9_reg_2908 | done_8_fu_1471_p2);

assign done_fu_747_p2 = (len_fu_738_p2 ^ 1'd1);

assign factor_fu_520_p3 = {{present_window_13_fu_310}, {1'd0}};

assign i_2_fu_641_p2 = (i_1_reg_2651 + 32'd1);

assign icmp_ln168_10_fu_989_p2 = ((tmp_10_fu_980_p4 != new_byte_reg_2768) ? 1'b1 : 1'b0);

assign icmp_ln168_12_fu_1026_p2 = ((tmp_13_fu_1017_p4 != present_window_12_load_reg_2671_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_13_fu_1040_p2 = ((tmp_14_fu_1031_p4 != present_window_13_load_reg_2685_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_14_fu_1054_p2 = ((tmp_15_fu_1045_p4 != present_window_14_load_reg_2699_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_15_fu_1068_p2 = ((tmp_16_fu_1059_p4 != present_window_15_load_reg_2736) ? 1'b1 : 1'b0);

assign icmp_ln168_16_fu_1082_p2 = ((tmp_17_fu_1073_p4 != new_byte_reg_2768) ? 1'b1 : 1'b0);

assign icmp_ln168_18_fu_1119_p2 = ((tmp_19_fu_1110_p4 != present_window_12_load_reg_2671_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_19_fu_1133_p2 = ((tmp_20_fu_1124_p4 != present_window_13_load_reg_2685_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_1_fu_798_p2 = ((tmp_3_fu_789_p4 != present_window_13_load_reg_2685_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_20_fu_1147_p2 = ((tmp_21_fu_1138_p4 != present_window_14_load_reg_2699_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_21_fu_1161_p2 = ((tmp_22_fu_1152_p4 != present_window_15_load_reg_2736) ? 1'b1 : 1'b0);

assign icmp_ln168_22_fu_1175_p2 = ((tmp_23_fu_1166_p4 != new_byte_reg_2768) ? 1'b1 : 1'b0);

assign icmp_ln168_24_fu_1218_p2 = ((tmp_25_fu_1209_p4 != present_window_12_load_reg_2671_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_25_fu_1238_p2 = ((tmp_26_fu_1229_p4 != present_window_13_load_reg_2685_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_26_fu_1252_p2 = ((tmp_27_fu_1243_p4 != present_window_14_load_reg_2699_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_27_fu_1266_p2 = ((tmp_28_fu_1257_p4 != present_window_15_load_reg_2736) ? 1'b1 : 1'b0);

assign icmp_ln168_28_fu_1280_p2 = ((tmp_29_fu_1271_p4 != new_byte_reg_2768) ? 1'b1 : 1'b0);

assign icmp_ln168_2_fu_824_p2 = ((tmp_4_fu_815_p4 != present_window_14_load_reg_2699_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_30_fu_1317_p2 = ((tmp_31_fu_1308_p4 != present_window_12_load_reg_2671_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_31_fu_1331_p2 = ((tmp_32_fu_1322_p4 != present_window_13_load_reg_2685_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_32_fu_1345_p2 = ((tmp_33_fu_1336_p4 != present_window_14_load_reg_2699_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_33_fu_1359_p2 = ((tmp_34_fu_1350_p4 != present_window_15_load_reg_2736) ? 1'b1 : 1'b0);

assign icmp_ln168_34_fu_1373_p2 = ((tmp_35_fu_1364_p4 != new_byte_reg_2768) ? 1'b1 : 1'b0);

assign icmp_ln168_3_fu_838_p2 = ((tmp_5_fu_829_p4 != present_window_15_load_reg_2736) ? 1'b1 : 1'b0);

assign icmp_ln168_4_fu_852_p2 = ((tmp_6_fu_843_p4 != new_byte_reg_2768) ? 1'b1 : 1'b0);

assign icmp_ln168_6_fu_899_p2 = ((tmp_9_fu_890_p4 != present_window_12_load_reg_2671_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_7_fu_935_p2 = ((tmp_s_fu_926_p4 != present_window_13_load_reg_2685_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_8_fu_961_p2 = ((tmp_7_fu_952_p4 != present_window_14_load_reg_2699_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_9_fu_975_p2 = ((tmp_1_fu_966_p4 != present_window_15_load_reg_2736) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_762_p2 = ((tmp_2_fu_753_p4 != present_window_12_load_reg_2671_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln178_1_fu_1508_p2 = ((currIdx_reg_reg_2830 > zext_ln161_1_fu_1459_p1) ? 1'b1 : 1'b0);

assign icmp_ln178_2_fu_1873_p2 = ((currIdx_reg_reg_2830 > zext_ln161_2_fu_1836_p1) ? 1'b1 : 1'b0);

assign icmp_ln178_3_fu_1928_p2 = ((currIdx_reg_reg_2830 > zext_ln161_3_fu_1905_p1) ? 1'b1 : 1'b0);

assign icmp_ln178_4_fu_1986_p2 = ((currIdx_reg_reg_2830 > zext_ln161_4_fu_1954_p1) ? 1'b1 : 1'b0);

assign icmp_ln178_5_fu_2015_p2 = ((currIdx_reg_reg_2830 > zext_ln161_5_fu_2012_p1) ? 1'b1 : 1'b0);

assign icmp_ln178_fu_1427_p2 = ((currIdx_reg_reg_2830 > zext_ln161_fu_1378_p1) ? 1'b1 : 1'b0);

assign icmp_ln179_1_fu_1528_p2 = ((tmp_36_fu_1518_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_2_fu_1893_p2 = ((tmp_38_fu_1883_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_3_fu_1948_p2 = ((tmp_40_fu_1938_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_4_fu_2006_p2 = ((tmp_42_fu_1996_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_5_fu_2035_p2 = ((tmp_44_fu_2025_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_fu_1447_p2 = ((tmp_fu_1437_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_1_fu_1812_p2 = ((match_offset_1_fu_1807_p2 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_2_fu_2121_p2 = ((match_offset_2_reg_3198 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_3_fu_2270_p2 = ((match_offset_3_reg_3301 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_4_fu_2297_p2 = ((match_offset_4_fu_2292_p2 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_5_fu_2462_p2 = ((match_offset_5_reg_3340 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_fu_1769_p2 = ((match_offset_reg_3087 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln185_10_fu_2467_p2 = ((len_71_fu_2447_p3 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln185_11_fu_2473_p2 = ((match_offset_5_reg_3340 < 32'd4097) ? 1'b1 : 1'b0);

assign icmp_ln185_1_fu_1780_p2 = ((match_offset_reg_3087 < 32'd4097) ? 1'b1 : 1'b0);

assign icmp_ln185_2_fu_1818_p2 = ((len_67_fu_1800_p3 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln185_3_fu_1824_p2 = ((match_offset_1_fu_1807_p2 < 32'd4097) ? 1'b1 : 1'b0);

assign icmp_ln185_4_fu_2126_p2 = ((len_68_fu_2106_p3 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln185_5_fu_2132_p2 = ((match_offset_2_reg_3198 < 32'd4097) ? 1'b1 : 1'b0);

assign icmp_ln185_6_fu_2275_p2 = ((len_69_fu_2256_p3 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln185_7_fu_2281_p2 = ((match_offset_3_reg_3301 < 32'd4097) ? 1'b1 : 1'b0);

assign icmp_ln185_8_fu_2303_p2 = ((len_70_reg_3232 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln185_9_fu_2308_p2 = ((match_offset_4_fu_2292_p2 < 32'd4097) ? 1'b1 : 1'b0);

assign icmp_ln185_fu_1774_p2 = ((len_66_fu_1762_p3 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln191_1_fu_2191_p2 = ((len_68_fu_2106_p3 > match_length_3_fu_2185_p3) ? 1'b1 : 1'b0);

assign icmp_ln191_2_fu_2364_p2 = ((len_69_fu_2256_p3 > match_length_5_fu_2359_p3) ? 1'b1 : 1'b0);

assign icmp_ln191_3_fu_2484_p2 = ((len_70_reg_3232 > match_length_7_reg_3352) ? 1'b1 : 1'b0);

assign icmp_ln191_4_fu_2510_p2 = ((len_71_fu_2447_p3 > match_length_9_fu_2504_p3) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_2165_p2 = ((len_67_reg_3165 > match_length_1_reg_3275) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_503_p2 = ((i_fu_298 < sub27) ? 1'b1 : 1'b0);

assign len_11_fu_875_p2 = ((tmp_8_fu_866_p4 == present_window_11_load_reg_2657_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign len_12_fu_910_p3 = ((len_11_fu_875_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign len_13_fu_918_p3 = ((done_6_fu_904_p2[0:0] == 1'b1) ? zext_ln168_1_fu_880_p1 : len_12_fu_910_p3);

assign len_14_fu_946_p2 = (len_13_fu_918_p3 + 2'd1);

assign len_15_fu_1462_p3 = ((done_7_reg_2892[0:0] == 1'b1) ? len_13_reg_2887 : len_14_reg_2898);

assign len_16_fu_1475_p2 = (zext_ln165_1_fu_1467_p1 + 3'd1);

assign len_17_fu_1481_p3 = ((done_8_fu_1471_p2[0:0] == 1'b1) ? zext_ln165_1_fu_1467_p1 : len_16_fu_1475_p2);

assign len_18_fu_1494_p2 = (len_17_fu_1481_p3 + 3'd1);

assign len_19_fu_1500_p3 = ((done_9_fu_1489_p2[0:0] == 1'b1) ? len_17_fu_1481_p3 : len_18_fu_1494_p2);

assign len_1_fu_773_p3 = ((len_fu_738_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign len_20_fu_1795_p2 = (len_19_reg_3099 + 3'd1);

assign len_22_fu_1012_p2 = ((tmp_12_fu_1003_p4 == present_window_11_load_reg_2657_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign len_23_fu_1547_p3 = ((len_22_reg_2923[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign len_24_fu_1554_p3 = ((done_11_fu_1542_p2[0:0] == 1'b1) ? zext_ln168_2_fu_1534_p1 : len_23_fu_1547_p3);

assign len_25_fu_1567_p2 = (len_24_fu_1554_p3 + 2'd1);

assign len_26_fu_1573_p3 = ((done_12_fu_1562_p2[0:0] == 1'b1) ? len_24_fu_1554_p3 : len_25_fu_1567_p2);

assign len_27_fu_1842_p2 = (zext_ln165_2_fu_1839_p1 + 3'd1);

assign len_28_fu_1848_p3 = ((done_13_reg_3125[0:0] == 1'b1) ? zext_ln165_2_fu_1839_p1 : len_27_fu_1842_p2);

assign len_29_fu_1859_p2 = (len_28_fu_1848_p3 + 3'd1);

assign len_2_fu_781_p3 = ((done_1_fu_767_p2[0:0] == 1'b1) ? zext_ln168_fu_743_p1 : len_1_fu_773_p3);

assign len_30_fu_1865_p3 = ((done_14_fu_1855_p2[0:0] == 1'b1) ? len_28_fu_1848_p3 : len_29_fu_1859_p2);

assign len_31_fu_2101_p2 = (len_30_reg_3182 + 3'd1);

assign len_33_fu_1105_p2 = ((tmp_18_fu_1096_p4 == present_window_11_load_reg_2657_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign len_34_fu_1599_p3 = ((len_33_reg_2960[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign len_35_fu_1606_p3 = ((done_16_fu_1594_p2[0:0] == 1'b1) ? zext_ln168_3_fu_1586_p1 : len_34_fu_1599_p3);

assign len_36_fu_1619_p2 = (len_35_fu_1606_p3 + 2'd1);

assign len_37_fu_1625_p3 = ((done_17_fu_1614_p2[0:0] == 1'b1) ? len_35_fu_1606_p3 : len_36_fu_1619_p2);

assign len_38_fu_1911_p2 = (zext_ln165_3_fu_1908_p1 + 3'd1);

assign len_39_fu_1917_p3 = ((done_18_reg_3136[0:0] == 1'b1) ? zext_ln165_3_fu_1908_p1 : len_38_fu_1911_p2);

assign len_3_fu_809_p2 = (len_2_fu_781_p3 + 2'd1);

assign len_40_fu_2143_p2 = (len_39_reg_3205 + 3'd1);

assign len_41_fu_2148_p3 = ((done_19_reg_3211[0:0] == 1'b1) ? len_39_reg_3205 : len_40_fu_2143_p2);

assign len_42_fu_2154_p2 = (len_41_fu_2148_p3 + 3'd1);

assign len_44_fu_1198_p2 = ((tmp_24_fu_1189_p4 == present_window_11_load_reg_2657_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign len_45_fu_1641_p3 = ((len_44_reg_2997[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign len_46_fu_1648_p3 = ((done_21_reg_3003[0:0] == 1'b1) ? zext_ln168_4_fu_1638_p1 : len_45_fu_1641_p3);

assign len_47_fu_1659_p2 = (len_46_fu_1648_p3 + 2'd1);

assign len_48_fu_1665_p3 = ((done_22_fu_1655_p2[0:0] == 1'b1) ? len_46_fu_1648_p3 : len_47_fu_1659_p2);

assign len_49_fu_1682_p2 = (zext_ln165_4_fu_1673_p1 + 3'd1);

assign len_4_fu_1381_p3 = ((done_2_reg_2856[0:0] == 1'b1) ? len_2_reg_2851 : len_3_reg_2862);

assign len_50_fu_1688_p3 = ((done_23_fu_1677_p2[0:0] == 1'b1) ? zext_ln165_4_fu_1673_p1 : len_49_fu_1682_p2);

assign len_51_fu_1957_p2 = (len_50_reg_3142 + 3'd1);

assign len_52_fu_1962_p3 = ((done_24_reg_3148[0:0] == 1'b1) ? len_50_reg_3142 : len_51_fu_1957_p2);

assign len_53_fu_1972_p2 = (len_52_fu_1962_p3 + 3'd1);

assign len_55_fu_1303_p2 = ((tmp_30_fu_1294_p4 == present_window_11_load_reg_2657_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign len_56_fu_1714_p3 = ((len_55_reg_3034[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign len_57_fu_1721_p3 = ((done_26_fu_1709_p2[0:0] == 1'b1) ? zext_ln168_5_fu_1701_p1 : len_56_fu_1714_p3);

assign len_58_fu_1734_p2 = (len_57_fu_1721_p3 + 2'd1);

assign len_59_fu_1740_p3 = ((done_27_fu_1729_p2[0:0] == 1'b1) ? len_57_fu_1721_p3 : len_58_fu_1734_p2);

assign len_5_fu_1394_p2 = (zext_ln165_fu_1386_p1 + 3'd1);

assign len_60_fu_2323_p2 = (zext_ln165_5_fu_2320_p1 + 3'd1);

assign len_61_fu_2329_p3 = ((done_28_reg_3159[0:0] == 1'b1) ? zext_ln165_5_fu_2320_p1 : len_60_fu_2323_p2);

assign len_62_fu_2340_p2 = (len_61_fu_2329_p3 + 3'd1);

assign len_63_fu_2346_p3 = ((done_29_fu_2336_p2[0:0] == 1'b1) ? len_61_fu_2329_p3 : len_62_fu_2340_p2);

assign len_64_fu_2442_p2 = (len_63_reg_3334 + 3'd1);

assign len_66_fu_1762_p3 = ((or_ln168_fu_1753_p2[0:0] == 1'b1) ? len_8_reg_3071 : len_9_fu_1757_p2);

assign len_67_fu_1800_p3 = ((or_ln168_5_fu_1791_p2[0:0] == 1'b1) ? len_19_reg_3099 : len_20_fu_1795_p2);

assign len_68_fu_2106_p3 = ((or_ln168_10_fu_2097_p2[0:0] == 1'b1) ? len_30_reg_3182 : len_31_fu_2101_p2);

assign len_69_fu_2256_p3 = ((or_ln168_15_fu_2252_p2[0:0] == 1'b1) ? len_41_reg_3291 : len_42_reg_3296);

assign len_6_fu_1400_p3 = ((done_3_fu_1390_p2[0:0] == 1'b1) ? zext_ln165_fu_1386_p1 : len_5_fu_1394_p2);

assign len_70_fu_1978_p3 = ((or_ln168_20_fu_1968_p2[0:0] == 1'b1) ? len_52_fu_1962_p3 : len_53_fu_1972_p2);

assign len_71_fu_2447_p3 = ((or_ln168_25_fu_2438_p2[0:0] == 1'b1) ? len_63_reg_3334 : len_64_fu_2442_p2);

assign len_7_fu_1413_p2 = (len_6_fu_1400_p3 + 3'd1);

assign len_8_fu_1419_p3 = ((done_4_fu_1408_p2[0:0] == 1'b1) ? len_6_fu_1400_p3 : len_7_fu_1413_p2);

assign len_9_fu_1757_p2 = (len_8_reg_3071 + 3'd1);

assign len_fu_738_p2 = ((trunc_ln168_fu_735_p1 == present_window_11_load_reg_2657_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign match_length_11_fu_2585_p3 = ((and_ln191_5_reg_3383[0:0] == 1'b1) ? len_71_reg_3368 : match_length_9_reg_3378);

assign match_length_1_fu_2071_p3 = ((and_ln191_fu_2065_p2[0:0] == 1'b1) ? len_66_fu_1762_p3 : 3'd0);

assign match_length_3_fu_2185_p3 = ((and_ln191_1_fu_2180_p2[0:0] == 1'b1) ? len_67_reg_3165 : match_length_1_reg_3275);

assign match_length_5_fu_2359_p3 = ((and_ln191_2_reg_3313[0:0] == 1'b1) ? len_68_reg_3286 : match_length_3_reg_3308);

assign match_length_7_fu_2398_p3 = ((and_ln191_3_fu_2392_p2[0:0] == 1'b1) ? len_69_fu_2256_p3 : match_length_5_fu_2359_p3);

assign match_length_9_fu_2504_p3 = ((and_ln191_4_fu_2499_p2[0:0] == 1'b1) ? len_70_reg_3232 : match_length_7_reg_3352);

assign match_offset_1_fu_1807_p2 = ($signed(sub_ln179_1_reg_3110) + $signed(32'd4294967295));

assign match_offset_2_fu_1899_p2 = ($signed(sub_ln179_2_fu_1878_p2) + $signed(32'd4294967295));

assign match_offset_3_fu_2160_p2 = ($signed(sub_ln179_3_reg_3222) + $signed(32'd4294967295));

assign match_offset_4_fu_2292_p2 = ($signed(sub_ln179_4_reg_3245) + $signed(32'd4294967295));

assign match_offset_5_fu_2354_p2 = ($signed(sub_ln179_5_reg_3260) + $signed(32'd4294967295));

assign match_offset_fu_1453_p2 = ($signed(sub_ln179_fu_1432_p2) + $signed(32'd4294967295));

assign or_ln168_10_fu_2097_p2 = (icmp_ln168_16_reg_2950 | done_14_reg_3177);

assign or_ln168_15_fu_2252_p2 = (icmp_ln168_22_reg_2987_pp0_iter2_reg | done_19_reg_3211);

assign or_ln168_20_fu_1968_p2 = (icmp_ln168_28_reg_3024 | done_24_reg_3148);

assign or_ln168_25_fu_2438_p2 = (icmp_ln168_34_reg_3061_pp0_iter2_reg | done_29_reg_3329);

assign or_ln168_5_fu_1791_p2 = (icmp_ln168_10_reg_2913 | done_9_reg_3094);

assign or_ln168_fu_1753_p2 = (icmp_ln168_4_reg_2877 | done_4_reg_3066);

assign or_ln185_1_fu_1830_p2 = (icmp_ln185_3_fu_1824_p2 | icmp_ln185_2_fu_1818_p2);

assign or_ln185_2_fu_2137_p2 = (icmp_ln185_5_fu_2132_p2 | icmp_ln185_4_fu_2126_p2);

assign or_ln185_3_fu_2286_p2 = (icmp_ln185_7_fu_2281_p2 | icmp_ln185_6_fu_2275_p2);

assign or_ln185_4_fu_2314_p2 = (icmp_ln185_9_fu_2308_p2 | icmp_ln185_8_fu_2303_p2);

assign or_ln185_5_fu_2478_p2 = (icmp_ln185_11_fu_2473_p2 | icmp_ln185_10_fu_2467_p2);

assign or_ln185_fu_1785_p2 = (icmp_ln185_fu_1774_p2 | icmp_ln185_1_fu_1780_p2);

assign or_ln191_1_fu_2548_p2 = (and_ln191_3_reg_3347 | and_ln191_2_reg_3313);

assign or_ln191_2_fu_2239_p2 = (and_ln191_reg_3270 | and_ln191_1_fu_2180_p2);

assign or_ln191_3_fu_2572_p2 = (or_ln191_fu_2544_p2 | or_ln191_1_fu_2548_p2);

assign or_ln191_fu_2544_p2 = (and_ln191_5_reg_3383 | and_ln191_4_reg_3373);

assign present_window_11_out = present_window_11_load_reg_2657_pp0_iter2_reg;

assign present_window_12_out = present_window_12_load_reg_2671_pp0_iter2_reg;

assign present_window_13_out = present_window_13_load_reg_2685_pp0_iter2_reg;

assign present_window_14_cast6_fu_516_p1 = present_window_14_fu_314;

assign present_window_14_out = present_window_14_load_reg_2699_pp0_iter2_reg;

assign present_window_15_out = present_window_15_load_reg_2736_pp0_iter2_reg;

assign select_ln191_1_fu_2558_p3 = ((and_ln191_5_reg_3383[0:0] == 1'b1) ? trunc_ln191_2_fu_2552_p1 : trunc_ln191_3_fu_2555_p1);

assign select_ln191_2_fu_2423_p3 = ((and_ln191_3_fu_2392_p2[0:0] == 1'b1) ? trunc_ln191_4_fu_2417_p1 : trunc_ln191_5_fu_2420_p1);

assign select_ln191_3_fu_2565_p3 = ((or_ln191_fu_2544_p2[0:0] == 1'b1) ? select_ln191_1_fu_2558_p3 : select_ln191_2_reg_3363);

assign select_ln191_4_fu_2244_p3 = ((or_ln191_2_fu_2239_p2[0:0] == 1'b1) ? select_ln191_fu_2231_p3 : 16'd0);

assign select_ln191_5_fu_2578_p3 = ((or_ln191_3_fu_2572_p2[0:0] == 1'b1) ? select_ln191_3_fu_2565_p3 : select_ln191_4_reg_3319);

assign select_ln191_fu_2231_p3 = ((and_ln191_1_fu_2180_p2[0:0] == 1'b1) ? trunc_ln191_fu_2225_p1 : trunc_ln191_1_fu_2228_p1);

assign shl_ln1_fu_565_p3 = {{present_window_12_load_reg_2671}, {3'd0}};

assign shl_ln_fu_558_p3 = {{present_window_11_load_reg_2657}, {4'd0}};

assign sub_ln179_1_fu_1513_p2 = (currIdx_reg_reg_2830 - zext_ln161_1_fu_1459_p1);

assign sub_ln179_2_fu_1878_p2 = (currIdx_reg_reg_2830 - zext_ln161_2_fu_1836_p1);

assign sub_ln179_3_fu_1933_p2 = (currIdx_reg_reg_2830 - zext_ln161_3_fu_1905_p1);

assign sub_ln179_4_fu_1991_p2 = (currIdx_reg_reg_2830 - zext_ln161_4_fu_1954_p1);

assign sub_ln179_5_fu_2020_p2 = (currIdx_reg_reg_2830 - zext_ln161_5_fu_2012_p1);

assign sub_ln179_fu_1432_p2 = (currIdx_reg_reg_2830 - zext_ln161_fu_1378_p1);

assign tmp19_cast_fu_592_p1 = tmp2_fu_584_p3;

assign tmp1_fu_579_p2 = (zext_ln121_fu_576_p1 + present_window_14_cast6_reg_2716);

assign tmp2_fu_584_p3 = {{tmp1_fu_579_p2}, {2'd0}};

assign tmp_10_fu_980_p4 = {{dictReadValue_reg_reg_2779[119:112]}};

assign tmp_11_fu_2090_p3 = len_67_reg_3165[32'd2];

assign tmp_12_fu_1003_p4 = {{dictReadValue_reg_reg_2779[151:144]}};

assign tmp_13_fu_1017_p4 = {{dictReadValue_reg_reg_2779[159:152]}};

assign tmp_14_fu_1031_p4 = {{dictReadValue_reg_reg_2779[167:160]}};

assign tmp_15_fu_1045_p4 = {{dictReadValue_reg_reg_2779[175:168]}};

assign tmp_16_fu_1059_p4 = {{dictReadValue_reg_reg_2779[183:176]}};

assign tmp_17_fu_1073_p4 = {{dictReadValue_reg_reg_2779[191:184]}};

assign tmp_18_fu_1096_p4 = {{dictReadValue_reg_reg_2779[223:216]}};

assign tmp_19_fu_1110_p4 = {{dictReadValue_reg_reg_2779[231:224]}};

assign tmp_1_fu_966_p4 = {{dictReadValue_reg_reg_2779[111:104]}};

assign tmp_20_fu_1124_p4 = {{dictReadValue_reg_reg_2779[239:232]}};

assign tmp_21_fu_1138_p4 = {{dictReadValue_reg_reg_2779[247:240]}};

assign tmp_22_fu_1152_p4 = {{dictReadValue_reg_reg_2779[255:248]}};

assign tmp_23_fu_1166_p4 = {{dictReadValue_reg_reg_2779[263:256]}};

assign tmp_24_fu_1189_p4 = {{dictReadValue_reg_reg_2779[295:288]}};

assign tmp_25_fu_1209_p4 = {{dictReadValue_reg_reg_2779[303:296]}};

assign tmp_26_fu_1229_p4 = {{dictReadValue_reg_reg_2779[311:304]}};

assign tmp_27_fu_1243_p4 = {{dictReadValue_reg_reg_2779[319:312]}};

assign tmp_28_fu_1257_p4 = {{dictReadValue_reg_reg_2779[327:320]}};

assign tmp_29_fu_1271_p4 = {{dictReadValue_reg_reg_2779[335:328]}};

assign tmp_2_fu_753_p4 = {{dictReadValue_reg_reg_2779[15:8]}};

assign tmp_30_fu_1294_p4 = {{dictReadValue_reg_reg_2779[367:360]}};

assign tmp_31_fu_1308_p4 = {{dictReadValue_reg_reg_2779[375:368]}};

assign tmp_32_fu_1322_p4 = {{dictReadValue_reg_reg_2779[383:376]}};

assign tmp_33_fu_1336_p4 = {{dictReadValue_reg_reg_2779[391:384]}};

assign tmp_34_fu_1350_p4 = {{dictReadValue_reg_reg_2779[399:392]}};

assign tmp_35_fu_1364_p4 = {{dictReadValue_reg_reg_2779[407:400]}};

assign tmp_36_fu_1518_p4 = {{sub_ln179_1_fu_1513_p2[31:16]}};

assign tmp_37_fu_2113_p3 = len_68_fu_2106_p3[32'd2];

assign tmp_38_fu_1883_p4 = {{sub_ln179_2_fu_1878_p2[31:16]}};

assign tmp_39_fu_2262_p3 = len_69_fu_2256_p3[32'd2];

assign tmp_3_fu_789_p4 = {{dictReadValue_reg_reg_2779[23:16]}};

assign tmp_40_fu_1938_p4 = {{sub_ln179_3_fu_1933_p2[31:16]}};

assign tmp_41_fu_2431_p3 = len_70_reg_3232[32'd2];

assign tmp_42_fu_1996_p4 = {{sub_ln179_4_fu_1991_p2[31:16]}};

assign tmp_43_fu_2454_p3 = len_71_fu_2447_p3[32'd2];

assign tmp_44_fu_2025_p4 = {{sub_ln179_5_fu_2020_p2[31:16]}};

assign tmp_45_fu_2052_p3 = len_66_fu_1762_p3[32'd2];

assign tmp_4_fu_815_p4 = {{dictReadValue_reg_reg_2779[31:24]}};

assign tmp_5_fu_829_p4 = {{dictReadValue_reg_reg_2779[39:32]}};

assign tmp_6_fu_843_p4 = {{dictReadValue_reg_reg_2779[47:40]}};

assign tmp_7_fu_952_p4 = {{dictReadValue_reg_reg_2779[103:96]}};

assign tmp_8_fu_866_p4 = {{dictReadValue_reg_reg_2779[79:72]}};

assign tmp_9_fu_890_p4 = {{dictReadValue_reg_reg_2779[87:80]}};

assign tmp_fu_1437_p4 = {{sub_ln179_fu_1432_p2[31:16]}};

assign tmp_s_fu_926_p4 = {{dictReadValue_reg_reg_2779[95:88]}};

assign trunc_ln111_fu_617_p1 = add_ln123_5_fu_611_p2[1:0];

assign trunc_ln127_fu_691_p1 = dictReadValue_reg_fu_668_p11[359:0];

assign trunc_ln132_fu_705_p1 = currIdx_reg_fu_700_p2[23:0];

assign trunc_ln168_fu_735_p1 = dictReadValue_reg_reg_2779[7:0];

assign trunc_ln191_1_fu_2228_p1 = match_offset_reg_3087[15:0];

assign trunc_ln191_2_fu_2552_p1 = match_offset_5_reg_3340[15:0];

assign trunc_ln191_3_fu_2555_p1 = match_offset_4_reg_3324[15:0];

assign trunc_ln191_4_fu_2417_p1 = match_offset_3_reg_3301[15:0];

assign trunc_ln191_5_fu_2420_p1 = match_offset_2_reg_3198[15:0];

assign trunc_ln191_fu_2225_p1 = match_offset_1_reg_3172[15:0];

assign zext_ln111_fu_634_p1 = lshr_ln1_reg_2731;

assign zext_ln118_fu_508_p1 = present_window_11_fu_302;

assign zext_ln119_fu_512_p1 = present_window_12_fu_306;

assign zext_ln120_fu_572_p1 = shl_ln1_fu_565_p3;

assign zext_ln121_fu_576_p1 = present_window_13_load_reg_2685;

assign zext_ln123_1_fu_538_p1 = add_ln123_fu_532_p2;

assign zext_ln123_2_fu_548_p1 = add_ln123_1_fu_542_p2;

assign zext_ln123_3_fu_602_p1 = add_ln123_3_reg_2721;

assign zext_ln123_fu_528_p1 = factor_fu_520_p3;

assign zext_ln148_fu_2590_p1 = match_length_11_fu_2585_p3;

assign zext_ln161_1_fu_1459_p1 = compareIdx_1_reg_2882;

assign zext_ln161_2_fu_1836_p1 = compareIdx_2_reg_2918;

assign zext_ln161_3_fu_1905_p1 = compareIdx_3_reg_2955;

assign zext_ln161_4_fu_1954_p1 = compareIdx_4_reg_2992;

assign zext_ln161_5_fu_2012_p1 = compareIdx_5_reg_3029;

assign zext_ln161_fu_1378_p1 = compareIdx_reg_2846;

assign zext_ln165_1_fu_1467_p1 = len_15_fu_1462_p3;

assign zext_ln165_2_fu_1839_p1 = len_26_reg_3120;

assign zext_ln165_3_fu_1908_p1 = len_37_reg_3131;

assign zext_ln165_4_fu_1673_p1 = len_48_fu_1665_p3;

assign zext_ln165_5_fu_2320_p1 = len_59_reg_3154;

assign zext_ln165_fu_1386_p1 = len_4_fu_1381_p3;

assign zext_ln168_1_fu_880_p1 = len_11_fu_875_p2;

assign zext_ln168_2_fu_1534_p1 = len_22_reg_2923;

assign zext_ln168_3_fu_1586_p1 = len_33_reg_2960;

assign zext_ln168_4_fu_1638_p1 = len_44_reg_2997;

assign zext_ln168_5_fu_1701_p1 = len_55_reg_3034;

assign zext_ln168_fu_743_p1 = len_fu_738_p2;

always @ (posedge ap_clk) begin
    present_window_14_cast6_reg_2716[8] <= 1'b0;
end

endmodule //lz4CompressEngineRun_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_compress
